# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-CPAN-Meta
version:      1.40
version_from: 
installdirs:  site
requires:
    File::Spec:                    0.80
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
